sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: xin_takeout
    username: root
    password: 546712
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFgdBn3xqsZgStdCM9j
    access-key-secret: mUSrHB0u3FoFgFqfvgw2RXqYF5tlAy
    bucket-name: xintakeout
  redis:
    host: localhost
    port: 6379
    password: 546712
    database: 0
  wechat:
    appid: wx456cddabd6af2fac
    secret: 1fdb384d237eccffca1b1915c6d925e5
    mchid: your_dev_mchid
    mch-serial-no: your_dev_mch_serial_no
    private-key-file-path: /path/to/your/dev/private-key-file.pem
    api-v3-key: your_dev_api_v3_key
    we-chat-pay-cert-file-path: /path/to/your/dev/we-chat-pay-cert-file.pem
    notify-url: https://your-dev-notify-url.com
    refund-notify-url: https://your-dev-refund-notify-url.com
  shop:
    address: 太原市小店区山西大学东山校区
  baidu:
    ak: N7gLQVnhw2napHh9JOwdSsd7R570I5Wc