sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: xin_takeout
    username: root
    password: 546712
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFgdBn3xqsZgStdCM9j
    access-key-secret: mUSrHB0u3FoFgFqfvgw2RXqYF5tlAy
    bucket-name: xintakeout
  redis:
    host: localhost
    port: 6379
    password: 546712
    database: 0